name: "[W] Auto Create Approve PR"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout target branch"
        uses: actions/checkout@v4
        with:
          ref: main

      - name: "Checkout or create release branch"
        run: |
          git fetch
          git checkout --track -b update-main origin/main

      - name: "Find and replace ENV vars"
        run: |
          touch example.txt
          echo "Hello, World!" > example.txt

      - name: "Commit changes"
        run: |
          git config user.name ${{ github.actor }}@noreply.github.com
          git config user.email ${{ github.actor }}@noreply.github.com
          git add example.txt
          git commit -m "chore: Update A for B"
          git push origin HEAD

      - name: "Create pull request to INFRA"
        run: |
          pr_url=$(gh pr create --title "Update A for B" --body "" | awk '/Created pull request/ {print $4}')
          pr_number=$(basename "$pr_url")
          echo "PR_NUMBER=${pr_number}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_SUPERTOKEN }}

      - name: "Auto approve pr"
        run: |
          gh pr review ${{ env.PR_NUMBER }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Merge pr"
        run: |
          gh pr merge ${{ env.PR_NUMBER }} --merge --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
