name: Check PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash
          
          # Define the regex pattern for Conventional Commits
          pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-z \-]+\))?: .+'
          
          if [[ $PR_TITLE =~ $pattern ]]; then
            echo "PR title '$PR_TITLE' follows the Conventional Commits specification."
            exit 0
          else
            echo "Error: PR title '$PR_TITLE' does not follow the Conventional Commits specification."
            echo "It should start with one of: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
            echo "Then a colon and space, followed by a description."
            echo "And task number in the end."
            echo "Example: 'feat: add new button component #DFLOW-1234'"
            exit 1
          fi
