name: "[W] Auto Create Approve PR"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Find PR with release-fixes tag
        id: find-release-fixes-pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_SUPERTOKEN }}
          script: |
            const query = 'repo:airslateinc/qa-docuflow-tests is:pr is:open label:release-fixes';
            const result = await github.rest.search.issuesAndPullRequests({
              q: query
            });
            
            let releaseBranch = 'master';
            
            if (result.data.items.length > 0) {
              const pr = result.data.items[0];
              const prData = await github.rest.pulls.get({
                owner: 'airslateinc',
                repo: 'qa-docuflow-tests',
                pull_number: pr.number
              });
              
              releaseBranch = prData.data.head.ref;
              console.log(`Found release-fixes PR branch: ${releaseBranch}`);
            } else {
              console.log('No PR with release-fixes tag found, using master as fallback');
            }
            
            return releaseBranch;

      - name: Dump find-release-fixes-pr
        env:
          GITHUB_CONTEXT: ${{ steps.find-release-fixes-pr.outputs.result }}
        run: |
          echo "$GITHUB_CONTEXT"
