name: "[W] Auto Create Approve PR"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Find PR with release-fixes tag
        id: find-release-fixes-pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_SUPERTOKEN }}
          script: |
            const query = `
              query {
                search(query: "repo:airslateinc/qa-docuflow-tests is:pr is:open label:release-fixes", type: ISSUE, first: 1) {
                  nodes {
                    ... on PullRequest {
                      number
                      headRefName
                    }
                  }
                }
              }
            `;
            
            const result = await github.graphql(query);
            let releaseBranch = 'master';
            
            if (result.search.nodes.length > 0) {
              releaseBranch = result.search.nodes[0].headRefName;
              console.log(`Found release-fixes PR branch: ${releaseBranch}`);
            } else {
              console.log('No PR with release-fixes tag found, using master as fallback');
            }
            
            return releaseBranch;

      - name: Dump find-release-fixes-pr
        env:
          GITHUB_CONTEXT: ${{ steps.find-release-fixes-pr.outputs.result }}
        run: |
          echo "$GITHUB_CONTEXT"
