name: "check name composition"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout target branch1"
        uses: actions/checkout@v4
        with:
          ref: main

      - name: "Compose v-env title"
        uses: actions/github-script@v7
        with:
          script: |
            const name = 'release-dflow-' + (new Date()).toLocaleDateString('uk-Ua').replace('.20', '').replaceAll('.','');
            core.exportVariable('V_ENV_NAME', name);

      - name: log
        env:
          GITHUB_CONTEXT: ${{ env.V_ENV_NAME }}
        run: |
          echo "$GITHUB_CONTEXT"
