name: '[X] PR autoupdate'

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: false

# test 2
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: '${{ secrets.PERSONAL_GITHUB_SUPERTOKEN }}'
          PR_READY_STATE: 'ready_for_review'
