name: '[X] PR Check Title airSlate'

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened]

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - name: PR conventional name check
        uses: airslateinc/pr-conventional-name@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
