name: Auto process

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'main'

permissions:
  pull-requests: write

jobs:
  time-check:
    runs-on: ubuntu-latest
    if: github.head_ref == 'translated_master'
    outputs:
      businessTime: ${{ steps.business-time.outputs.result }}
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.1
        id: current-time
        with:
          format: d-H

      - name: Check Business time
        uses: actions/github-script@v6
        id: business-time
        with:
          result-encoding: string
          script: |
            const [ day, hours ] = ('${{ steps.current-time.outputs.formattedTime }}').split('-');

            return 'no';

  pr-process:
    runs-on: ubuntu-latest
    needs: [time-check]
    if: ${{ needs.time-check.outputs.businessTime == 'no' }}
    steps:
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pr
        with:
          branch: translated_master

      - name: Approve Pull Request
        if: ${{ steps.find-pr.outputs.number != '' }}
        uses: hmarr/auto-approve-action@v2
        with:
          pull-request-number: ${{ steps.find-pr.outputs.number }}

