name: "[L] Deps Update"

on:
  pull_request:
    types: [labeled]

env:
  PACKAGE: 'creator-addons-app'

jobs:
  process-sync-pr:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'update-deps'
    steps:

      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          ref: release-next

      - name: "NodeJS cached setup"
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: "Setup NPM registry"
        run: |
          npm config set registry https://artifactory.infrateam.xyz/artifactory/api/npm/npm/
          npm config set always-auth true
          echo "//artifactory.infrateam.xyz/artifactory/api/npm/npm/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: "Upgrade package version to latest"
        run: |
          yarn upgrade ${{ env.PACKAGE }} --latest

      - name: "Push updated dep"
        env:
          GITHUB_GLOBAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name ${{ github.actor }}@noreply.github.com
          git config user.email ${{ github.actor }}@noreply.github.com
          git commit -a -m 'chore: update deps'
          git push origin release-next

      - name: "Delete pull request label"
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'update-deps'

