name: "[L] Webhook sent by label"

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'Prometey:deploy'
    steps:
      - name: "Modify pull request description"
        uses: actions/github-script@v6
        id: pull-body
        with:
          script: |
            return (${{ toJson(github.event.pull_request.body) }}).includes('\n- [x] Prometey:')
              ? 'unmodified'
              : ${{ toJson(github.event.pull_request.body) }} + "\n- [x] Prometey:"

      - name: "Create trigger payload"
        uses: actions/github-script@v6
        id: build-payload
        with:
          script: |
            return {
              "branch-name": "${{ github.head_ref }}",
              "repo-name": "${{ github.repository }}",
              "pull-number": "${{ github.event.number }}",
              "pull-body": ${{ steps.pull-body.outputs.result }},
            }

      - name: "Trigger middle webhook"
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/dispatches
          repository: ZakrepaShe/gh-actions-check
          event_type: 'webhook-middle'
          headers: '{ "X-GitHub-Api-Version": "2022-11-28" }'
          client_payload: ${{ steps.build-payload.outputs.result }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
