name: "[X] Webhook receive and resent"

on:
  repository_dispatch:
    types:
      - webhook-middle

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Re-form payload for finish webhook"
        uses: actions/github-script@v6
        id: build-payload
        with:
          script: |
            return {
              "branch-name": "${{ github.event.client_payload.branch-name }}",
              "repo-name": "${{ github.event.client_payload.repo-name }}",
              "pull-number": "${{ github.event.client_payload.pull-number }}",
              "pull-body": "${{ github.event.client_payload.pull-body }}"
            }

      - name: "Trigger finish webhook"
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/dispatches
          repository: ZakrepaShe/gh-actions-check
          event_type: 'webhook-finish'
          headers: '{ "X-GitHub-Api-Version": "2022-11-28" }'
          client_payload: ${{ steps.build-payload.outputs.result }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
